apiVersion: v1
kind: Service
metadata:
  name: javagithub-service
  labels: 
    name: tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31500
    protocol: TCP
  selector:
    name: tomcat
