name: Build and Test

on:
  push:
    branches:
      - master
permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout k8 manifests repo
        uses: actions/checkout@v2
        with:
          repository: mpakeeru/argo-cd
          ref: master  # Specify the branch or commit you want to checkout
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit file and commit changes
        run: |
          # Update the file content
          sed -i 's|\(image:\) .*|\1 mamathasama/javagithub:build-${{ github.run_number }}|' tomcatwebapp-deployment.yml
          # Configure Git
          git config --global user.email "mamathasama@hotmail.com"
          git config --global user.name "mpakeeru"
          # Add and commit changes
          git add tomcatwebapp-deployment.yml
          git commit -m "Update image version wit ${{ github.run_number }} "
          git push
         # git remote set-url origin "https://${{ github.actor }}:${{ secrets.MY_GITHUB_TOKEN }}@github.com/mpakeeru/argo-cd.git"
         # git push https://mpakeeru:${MY_GITHUB_TOKEN}@github.com/mpakeeru/argo-cd.git HEAD:master
        #env:
         # MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
